### ISSUE TITLE
[Bug] dontClearChatHistory开启后在carpet指令列表换行时无法显示

### ISSUE THREAD

**Issue by fractures202** [Nyan-Work/oh-my-minecraft-client#1]
### Minecraft Version

1.19.3

### OMMC Version

oh-my-minecraft-client-1.19.3-0.5.267+4c2f3b1-beta

### Description

![QQ拼音截图20230325032822](https://user-images.githubusercontent.com/88050097/227622304-dd7d837d-aef8-4d13-8a29-28b1c293e3ea.png)
![QQ拼音截图20230325032949](https://user-images.githubusercontent.com/88050097/227622328-9f4d7b76-f509-4280-a1d8-79e3201f6ad4.png)

### To Reproduce

如图

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
尝试 [0.5.269+957c0dd](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.12) 版本。
