### ISSUE TITLE
[Question] MC 1.20.1 O+C无法打开配置界面，模组菜单里面也无法配置

### ISSUE THREAD

**Issue by Ackerven** [Nyan-Work/oh-my-minecraft-client#11]
### Question Type

Usages

### Description

Minecraft 的版本是 `1.20.1`
OMMC 的版本是 `0.5.292+eec667c`
MagicLib 的版本是 `0.7.346+e235d92`

![无标题1](https://github.com/Nyan-Work/oh-my-minecraft-client/assets/70303900/9531d40c-1faa-48f5-ab86-86a5c6bfa92c)

**Comment by Hendrix-Shen** [comment]
与 #9 重复。
