### ISSUE TITLE
[Bug] 与 sodium 0.5.0 不兼容

### ISSUE THREAD

**Issue by wafarm** [Nyan-Work/oh-my-minecraft-client#16]
### Minecraft Version

1.20.1

### OMMC Version

0.5.304+a200fcc-beta （最新的actions build）

### Description

在仅安装必要的依赖、该模组和 sodium 时，在加载世界后进入瞬间会直接崩溃，根据日志是 mixin `feature.worldEaterMineHelper.sodium.MixinBlockRenderer` 应用失败，具体为 `@Shadow method renderModel` 不存在，猜测为 sodium 更新修改了相关方法，我对渲染不熟，不能提供可能的解决方法。

### To Reproduce

将 mod 和 sodium 0.5.0 同时安装，随意进入一个世界（单人或服务器均可）

### Expected behavior

正常进入世界

### Log

太长了 用了pastebin，[log](https://mclo.gs/JdnU6ZN).

使用了 Quilt Mod Loader，应该没有影响

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by wafarm** [comment]
Update: `renderModel` 的签名中返回类型由 `boolean` 改为了 `void`。但直接改会导致对 0.5.0 以下版本不支持。

**Comment by Hendrix-Shen** [comment]
请尝试此版本：[0.5.308+9e3633a](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.31)。目前已在下属环境通过测试： 
- MC 1.20.1 + Fabric API 0.86.1+1.20.1 + Sodium mc1.20.1-0.5.0
- MC 1.20.1 + Fabric API 0.86.1+1.20.1 + Sodium mc1.20-0.4.10+build.27

其他版本未经测试，如有问题可继续在此报告

**Comment by wafarm** [comment]
一切正常，应该没有问题
