### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LangKeWAVE** [Nyan-Work/oh-my-minecraft-client#19]
### Minecraft Version

1.19.2

### OMMC Version

1.33.1

### Description

minihud翻译无法显示

### To Reproduce

下载预发布版并加载minihud

### Expected behavior

没汉化，加了汉化材质包也一样

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by LangKeWAVE** [comment]
ommc版本是oh-my-minecraft-client-all-0.5.315+5bc7e1a-beta

**Comment by LangKeWAVE** [comment]
或者是masagadget有问题

**Comment by Hendrix-Shen** [comment]
OMMC 不提供 MiniHUD 汉化功能，请尝试从 GitHub Actions 更新 Masa Gadget，如果问题依然存在请在 Masa Gadget 仓库中报告问题。
