### ISSUE TITLE
[Bug] 部分模型位置和角度不正确

### ISSUE THREAD

**Issue by Phoupraw** [Nyan-Work/oh-my-minecraft-client#2]
### Minecraft Version

1.19.2

### OMMC Version

0.5.273+40a44e1-beta

### Description

[原issue](https://github.com/plusls/oh-my-minecraft-client/issues/77)

部分模型位置和角度不正确。没有开启世吞挖矿助手。
![2023-04-14_13 04 30](https://user-images.githubusercontent.com/50520903/231946391-0622fe85-63d7-4664-a715-6e93753041cd.png)

把`MixinJsonUnbakedModel`删掉后，模型就恢复正常了。

### To Reproduce

安装[更多的合成](https://www.mcmod.cn/class/1297.html)资源包和数据包，然后使用任意方式获取[多功能一体机](https://www.mcmod.cn/item/137191.html)或[合成器](https://www.mcmod.cn/item/135225.html)，并放置。

### Expected behavior

![2023-04-14_13 05 48](https://user-images.githubusercontent.com/50520903/231946439-02682c3e-7ead-4c2b-89bc-1b11c362fbec.png)

### Log

[latest.log](https://github.com/Nyan-Work/oh-my-minecraft-client/files/11230730/latest.log)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Phoupraw** [comment]
世吞挖矿助手白名单中只有以下：
- `_ore`
- `minecraft:ancient_debris`
- `minecraft:obsidian`

添加新的ID可以让对应方块也拥有镜像，移除现有ID可以让对应方块失去镜像，但是即使移除了所有ID，上述模型仍然不正确渲染。

**Comment by Hendrix-Shen** [comment]
尝试在 [0.5.304+a200fcc](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.29) 中修复，希望能正常工作。
