### ISSUE TITLE
[Bug] 整理仓库功能会在能打字的地方发出声音

### ISSUE THREAD

**Issue by wj9559** [Nyan-Work/oh-my-minecraft-client#23]
### Minecraft Version

1.20.1

### OMMC Version

1.20.1-0.5.319+3712d5c-beta

### Description

在有物品栏的界面整理成功时有声音没有声音字幕，物品栏不需要整理时会有声音字幕“发射器：发射失败”。
在可以打字的地方输入了整理键就会有声音和声音字幕出现，比如告示牌和配方书搜索时。

### To Reproduce

打命令时经常出现发射器的声音和声音字幕，但是身边没有发射器，换了不带Mod的纯净原版测试时发现没有该情况，应该是模组问题，测试了26键后发现只有整理仓库键有声音，禁用后问题消失。

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
在 [0.5.322+0dd74c1](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.44) 中修复。
