### ISSUE TITLE
[Bug] 容器无服务端支持预览不正常工作

### ISSUE THREAD

**Issue by acaciachan** [Nyan-Work/oh-my-minecraft-client#24]
### Minecraft Version

all

### OMMC Version

325

### Description

https://github.com/Nyan-Work/oh-my-minecraft-client/assets/73088428/89745445-b0d4-4383-b7ba-b7a69f7eecb0

本地的服务端，按容器预览会一直听到开容器的声音，在有些别的没有容器预览支持的服务器同样不正常，所有版本一起出的问题

另外还有个存在已久的问题，就是触发快捷键松开的太快的话，容器界面还是会显示的，可能是网络延时造成没有屏蔽掉，加个可调的应对网络延时的数值解决这个问题？

### To Reproduce

1

### Expected behavior

1

### Log

1

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
可能由 Masa Gadget 的 `容器预览时同步数据（仅客户端）(inventoryPreviewSyncDataClientOnly) ` 引起。Masa Gadget 侧针对此问题会暂缓修复。
