### ISSUE TITLE
[Bug] sortInventory 无法整理普通蜡烛/白蜡烛

### ISSUE THREAD

**Issue by honbey** [Nyan-Work/oh-my-minecraft-client#27]
### Minecraft Version

1.20.2

### OMMC Version

oh-my-minecraft-client-1.20.2-0.5.325+b4f9d2d-beta

### Description

背包/箱盒中存在未染色的普通蜡烛或白色蜡烛时，使用 R 键整理背包功能游戏会崩溃。

看了下日志和 mod 源码，`java.util.Map.get()` 报错，源码的 `get()` 方法不太安全，搜了下 Java 有个 `getOrDefault()` 方法，本地改动了下能正常排序了，不咋会 Java，就不提 PR 了
```java
if (SortInventoryUtil.bothContains("wool", ida, idb) ||
        SortInventoryUtil.bothContains("terracotta", ida, idb) ||
        SortInventoryUtil.bothContains("concrete", ida, idb) ||
        SortInventoryUtil.bothContains("candle", ida, idb)) {
    //LOGGER.debug("blockA.defaultMapColor(): '{}'", blockA.defaultMapColor());
    return SortInventoryUtil.MAP_COLOR_MAPPING.getOrDefault(
            //#if MC > 11502
            blockA.defaultMapColor()
            //#else
            //$$ ((AccessorBlock) blockA).getMaterialColor()
            //#endif
            , 0
    ) -
            SortInventoryUtil.MAP_COLOR_MAPPING.getOrDefault(
                    //#if MC > 11502
                    blockB.defaultMapColor()
                    //#else
                    //$$ ((AccessorBlock) blockB).getMaterialColor()
                    //#endif
            , 0
            );
}
```

在 `MAP_COLOR_MAPPING` 中 put `MapColor.CANDLE` /  `MapColor.CANDLES` 编译失败，本地 `./gradlew genSources` 没找到源码... 找到个 [Forge 的 JavaDocs](https://mcstreetguy.github.io/ForgeJavaDocs/1.20.2-latest/net/minecraft/world/level/material/MapColor.html) 看了 `MapColor` 这个类，没发现 `CANDLE` ，不确定是不是 MOJANG 的问题...

吐槽下 mod 设置的 debug 开关没啥用

### To Reproduce

背包/箱盒中存在未染色的普通蜡烛或白色蜡烛时，使用 sortInventory 功能

### Expected behavior

sort items properly

### Log

https://mclo.gs/NOas04N

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请尝试：[0.5.326+f766ee1](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.48)

**Comment by honbey** [comment]
已解决，多谢
