### ISSUE TITLE
[Question] 作者哥什么时候更新

### ISSUE THREAD

**Issue by xv137514** [Nyan-Work/oh-my-minecraft-client#37]
### Question Type

Others

### Description

哥求你了，什么时候可以更新1.20.6，没有ommc我会死的~

**Comment by BeadyTooth57254** [comment]
hhhhhhhhhh+1
孩子想吃一口1.20.6的ommc求求啦~~~~~

**Comment by Xieecao** [comment]
据本人所了解，该模组及其关联模组 PCA, Carpet-TCTC, MagicLib, MasaGadget, XMA 皆未更新

**Comment by BeadyTooth57254** [comment]
qwp好馋啊qaq

**Comment by niubikelashi** [comment]
多放个地方吧，这里的链接老是崩

**Comment by BeadyTooth57254** [comment]
> 据本人所了解，该模组及其关联模组 PCA， Carpet-TCTC， MagicLib， MasaGadget， XMA 皆未更新

MagicLib更新啦awa~

**Comment by FANXING-0710** [comment]
求更新

**Comment by StarlingLin** [comment]
求更新1.20.6

**Comment by Wuthering117** [comment]
求更新1.21qwq，没有ommc玩的太难受了

**Comment by XC084** [comment]
> 据本人所了解，该模组及其关联模组 PCA， Carpet-TCTC， MagicLib， MasaGadget， XMA 皆未更新

事实上,[masa的作者已经不想适配新版了](https://www.reddit.com/r/litematica/comments/1di4o3h/announcement_about_litematicas_future_and_updates/?rdt=64370),[新版本交给了第三方更新](https://github.com/sakura-ryoko)
所以如果可以的话,新版本用Sakura-Ryoko的移植版当前置,也基本没有改动

**Comment by Hendrix-Shen** [comment]
MagicLib 还处于重构阶段，模组比较多，代码要一行一行写，延迟更新，还望见谅！

**Comment by niubikelashi** [comment]
问题不大，慢慢来，等得起，不着急

**Comment by CMJNB** [comment]
> MagicLib 还处于重构阶段，模组比较多，代码要一行一行写，延迟更新，还望见谅！

[MagicLib](https://github.com/Hendrix-Shen/MagicLib/releases/tag/0.8)更新了🤩

**Comment by AilaSama** [comment]
我们需要1.21qaq

**Comment by star-bailu** [comment]
你好，邮件已收到，谢谢

**Comment by mistmoontf** [comment]
别急各位，慢慢等，作者重构需要时间

**Comment by AilaSama** [comment]
好的喵获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 Firefly_ ***@***.***>发送时间: 星期六, 七月 20, 2024 9:40:00 上午收件人: Nyan-Work/oh-my-minecraft-client ***@***.***>抄送: AilaSama ***@***.***>; Comment ***@***.***>主题: Re: [Nyan-Work/oh-my-minecraft-client] [Question] 作者哥什么时候更新 (Issue #37)
别急各位，慢慢等，作者重构需要时间

**Comment by Hendrix-Shen** [comment]
此问题将转移到 #42 进行处理。
