### ISSUE TITLE
[Bug] World Eater Mine Helper does not work with sodium

### ISSUE THREAD

**Issue by TyIuNnG** [Nyan-Work/oh-my-minecraft-client#4]
### Minecraft Version

1.19.3

### OMMC Version

oh-my-minecraft-client-0.5.280+1071c4b-beta

### Description

WorldEaterMineHelper doesn't work with sodium 0.4.9, but is working with 0.4.8. The issue doesn't cause game crash, just the block model does not render.

### To Reproduce

Install sodium 0.4.9 and turn on WorldEaterMineHelper

### Expected behavior

The block model of the whitelisted block should be rendered

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by TyIuNnG** [comment]
1.20.1 最新版ommc也還是顯示不出來 只能拔掉sodium才會有 應該是sodium在0.4.9的更新時改了甚麼之後就用不了worldEaterMineHelper了

OMMC version:
oh-my-minecraft-client-all-0.5.294+e12a73f-beta

**Comment by TyIuNnG** [comment]
換上的0.5.299 不過會崩
用0.5.296 也會崩

[crash-2023-07-27_18.59.07-client.txt](https://github.com/Nyan-Work/oh-my-minecraft-client/files/12181350/crash-2023-07-27_18.59.07-client.txt)

**Comment by Hendrix-Shen** [comment]
试一下[0.5.302+5944317](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.28)。

**Comment by TyIuNnG** [comment]
sodium有甚麼設定會導致看不到嗎? worldEaterMineHelper還是沒有反應
目前是用sodium 0.4.10

**Comment by Hendrix-Shen** [comment]
我这里测试是可以渲染了的。

**Comment by TyIuNnG** [comment]
有可能會是magiclib版本的關係嗎?

**Comment by Hendrix-Shen** [comment]
理论来说关系不是特别大，ommc没有使用太多的magiclib特性，因此只要能正常加载ommc就不应该是magiclib的问题

**Comment by TyIuNnG** [comment]
目前一樣是拔掉sodium之後就會正常

  [✔️] [投影打印机_宅闲鱼二改版]litematica-printer-1.20.1-20230628-2.4.jar
  [✔️] bedrock-miner-1.20.1-1.1.7.jar
  [✔️] Carpet-AMS-Addition-mc1.20.1-v2.2.1.jar
  [✔️] carpet-extra-1.20-1.4.115.jar
  [✔️] carpet-fixes-1.20-1.16.1.jar
  [✔️] carpet-shadow-1.10.2-MC1.20.1_build_36.jar
  [✔️] CarpetTCTCAddition-all-2.2.201+8009659-stable.jar
  [✔️] carpet-tis-addition-mc1.20.1-v1.49.0.jar
  [✔️] clientcommands-2.8.2.jar
  [✔️] cmdkeybind-1.6.3-1.20.jar
  [✔️] CommandGUIButtons-aio-2.1.0+build.148+ffcad3b.jar
  [✔️] continuity-3.0.0-beta.2+1.20.jar
  [✔️] enhancedblockentities-0.9+1.20.jar
  [✔️] essential-client-1.20.1-1.3.5.jar
  [✔️] ExtraPlayerRenderer-1.20.1-2.3.0.jar
  [✔️] fabric-api-0.85.0+1.20.1.jar
  [✔️] fabric-carpet-1.20-1.4.112+v230608.jar
  [✔️] fabric-language-kotlin-1.10.0+kotlin.1.9.0.jar
  [✔️] ferritecore-6.0.0-fabric.jar
  [✔️] indium-1.0.20+mc1.20.1.jar
  [✔️] InGameAccountSwitcher-Fabric-1.20-8.0.2.jar
  [✔️] InventoryProfilesNext-fabric-1.20-1.10.6.jar
  [✔️] invhud.fabric.1.20-3.4.13.jar
  [✔️] iris-mc1.20-1.6.4.jar
  [✔️] isometric-renders-0.4.4+1.20.jar
  [✔️] itemscroller-fabric-1.20.1-craftfix-1.2.7.jar
  [✔️] krypton-0.2.3.jar
  [✔️] lazydfu-0.1.3.jar
  [✔️] let-me-play-iris-1.0.1-dev.jar
  [✔️] LibGui-8.0.1+1.20.jar
  [✔️] libIPN-fabric-1.20-3.0.2.jar
  [✔️] litematica-fabric-1.20.1-0.15.3.jar
  [✔️] lithium-fabric-mc1.20.1-0.11.2.jar
  [✔️] magiclib-all-0.7.346+e235d92-stable.jar
  [✔️] malilib-fabric-1.20.1-0.16.1.jar
  [✔️] MasaGadget-all-3.2.311+aae0554-stable.jar
  [✔️] minihud-fabric-1.20.1-0.27.0.jar
  [✔️] modmenu-7.1.0.jar
  [✔️] NoChatReports-FABRIC-1.20.1-v2.2.2.jar
  [✔️] notenoughcrashes-4.4.4+1.20.1-fabric.jar
  [✔️] oh-my-minecraft-client-all-0.5.302+5944317-beta.jar
  [✔️] oldpotions-2.4+1.20.1.jar
  [✔️] owo-lib-0.11.0+1.20.jar
  [✔️] pistorder-mc1.20-v1.5.0-fabric.jar
  [✔️] PluslsCarpetAddition-all-0.3.169+6510223-beta.jar
  [✔️] reeses_sodium_options-1.5.1+mc1.20-build.74.jar
  [✔️] sodium-extra-0.4.20+mc1.20.1-build.103.jar
  [✔️] sodium-fabric-mc1.20-0.4.10+build.27.jar
  [✔️] spawnproofhelper-2.0.0.jar
  [✔️] starlight-1.1.2+fabric.dbc156f.jar
  [✔️] syncmatica-1.20.1-0.3.9.jar
  [✔️] tweakermore-mc1.20.1-v3.13.1.jar
  [✔️] tweakeroo-fabric-1.20.1-0.17.1.jar
  [✔️] viafabricplus-2.7.8.jar
  [✔️] voxelmap-1.20.1-1.12.11.jar
  [✔️] WorldEditCUI-1.20+01.jar
  [✔️] worldedit-mod-7.2.15.jar
  [✔️] wraith-colormeoutlines-1.1.2.jar

**Comment by Hendrix-Shen** [comment]
方便的话打包上传一下mods，明天到开发环境查一下，要看一下mixin导出。

**Comment by TyIuNnG** [comment]
https://www.mediafire.com/file/ivtozu3rh5ai5z1/mods.zip/file

**Comment by Hendrix-Shen** [comment]
![图片](https://github.com/Nyan-Work/oh-my-minecraft-client/assets/25112869/f13c7f2b-9a00-43d4-ac22-637108bf1d73)
我使用了你提供的模组包测试，是可以正常渲染的，难道说是光影的问题？

**Comment by TyIuNnG** [comment]
光影沒開呀?

**Comment by Hendrix-Shen** [comment]
我这边确实无法再复现这个问题。

**Comment by TyIuNnG** [comment]
我這邊有試到一個問題點是在options.txt
[options.txt](https://github.com/Nyan-Work/oh-my-minecraft-client/files/12190342/options.txt)

我如果把這個檔案砍掉就有用 不過具體是裡面哪一項造成的我就不太確定

**Comment by TyIuNnG** [comment]
好像是材質包的問題
如果把所有的材質包拔掉就有了 

我用的五個材質包裡面有三個都會導致看不到 紅顯 和兩個continuity附帶的材質包

**Comment by TyIuNnG** [comment]
[redstone+display1.20-V2edit.zip](https://github.com/Nyan-Work/oh-my-minecraft-client/files/12190598/redstone%2Bdisplay1.20-V2edit.zip)

**Comment by TyIuNnG** [comment]
材質包裡面有個optifine的資料夾 裡面有個emissive.properties 拿掉就有了
裡面就一行 suffix.emissive=_e
沒記錯應該是從vanilla tweaks上面抓來的

移除之後continuity也不要開就沒有問題了

**Comment by Hendrix-Shen** [comment]
这个没办法了，Continuity的方块发光，弄起来麻烦的很。
