### ISSUE TITLE
[Question] 想知道pluls老师的模组对于版本的支持

### ISSUE THREAD

**Issue by HoneyBlock** [Nyan-Work/oh-my-minecraft-client#48]
### Question Type

Others

### Description

对于 ommc 之后的版本还会有更新吗，或者有人能帮我指一条有1.21版本的仓库吗

**Comment by vocaloidkiss** [comment]
@HoneyBlock https://github.com/SkyDynamic/oh-my-minecraft-client

**Comment by vocaloidkiss** [comment]
建议关闭本issue，重复了

**Comment by vocaloidkiss** [comment]
发讨论而非议题
