### ISSUE TITLE
[Bug]  Incorrect work of inventory sorting

### ISSUE THREAD

**Issue by ItzSkyReed** [Nyan-Work/oh-my-minecraft-client#5]
### Minecraft Version

1 19 4

### OMMC Version

05.280

### Description

Mod sorts creative inventory tabs and some items disappear

### To Reproduce

Open create inventory, open any tab with items, trigger function that sort inventory. 

### Expected behavior

Nothing should happen

### Log

https://mclo.gs/XdhsFAo - it doesn't contain any errors

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by ItzSkyReed** [comment]
![image-2](https://github.com/Nyan-Work/oh-my-minecraft-client/assets/93844414/6f907a88-c2e5-4aa2-8c82-6ec0cb6f60ac)
![image-1](https://github.com/Nyan-Work/oh-my-minecraft-client/assets/93844414/dfc3c14c-822c-453c-8739-32e9a7a4c947)

**Comment by Hendrix-Shen** [comment]
Try this version: [0.5.288+4301778](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work/dev.22)

**Comment by ItzSkyReed** [comment]
thx
