### ISSUE TITLE
[Bug] 创造的物品栏可以被整理

### ISSUE THREAD

**Issue by 100210110** [Nyan-Work/oh-my-minecraft-client#6]
### Minecraft Version

1.19.4

### OMMC Version

oh-my-minecraft-client-1.19.4-0.5.282+2b353c9-beta,   xaero-map-addition-0.2.3

### Description

我的选取物品键设置的也是r键，在复制物品的时候，把我的物品栏都搞乱了，都错位了，而且缺少很多物品
![image](https://github.com/Nyan-Work/oh-my-minecraft-client/assets/104227884/cd502eda-1f86-4ea2-b542-da9bf783f27c)
![image](https://github.com/Nyan-Work/oh-my-minecraft-client/assets/104227884/42d6f5ed-3ad3-4f3b-8d8e-86841946e5f9)
上面是全部的mod

### To Reproduce

我曾在1.19.3触发这个问题，现在在1.19.4也触发了
具体就是对着创造的物品栏按下R键
为了排除是不是选取方块也设置成R的问题，我把选取方块改回默认，但是还是可以触发这个bug

### Log

这个并不会导致游戏崩溃，所以我不知道在哪里找到游戏日志，但只能重启游戏解决，造成很大麻烦。

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by YamaArashiHZ** [comment]
与#5 重复
