### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by fashion27** [Nyan-Work/oh-my-minecraft-client#9]
### Question Type

Usages

### Description

没有显示ommc的设置（）
![image](https://github.com/Nyan-Work/oh-my-minecraft-client/assets/109896502/74c8d000-c0f8-4d5d-be86-8ee5dcb802ea)

**Comment by Wudji** [comment]
我刚刚不是在群里说了，可能是我忘改oh-my-minecraft-client的fabric.mod.json导致无法被加载的。。。。。。

**Comment by fashion27** [comment]
不好意思 没有加群 那要怎么解决呢 谢谢

**Comment by fashion27** [comment]
> 我刚不是在群里说了，可能是我忘了改oh-my-minecraft-client的fabric.mod.json导致无法被加载的。。。。。。

抱歉没加群 那要怎么解决呢 谢谢

**Comment by Wudji** [comment]
> > 我刚不是在群里说了，可能是我忘了改oh-my-minecraft-client的fabric.mod.json导致无法被加载的。。。。。。
> 
> 抱歉没加群 那要怎么解决呢 谢谢

刚有人问过这个问题。。。认错人了，抱歉。
把ommc版本换成oh-my-minecraft-client-0.5.292+eec667c-beta.jar（https://github.com/Nyan-Work/oh-my-minecraft-client/actions/runs/5252759627）试试

**Comment by fashion27** [comment]
> > > 我刚不是在群里说了，可能是我忘了改oh-my-minecraft-client的fabric.mod.json导致无法被加载的。。。。。。
> > 
> > 
> > 抱住不加群 那要怎么解决呢 谢谢
> 
> 刚有人问过这个问题。。。认错了，抱抱。 把ommc版本替换成oh-my-minecraft-client-0.5.292+eec667c-beta.jar（[https://github.com/Nyan-Work/ oh-my-minecraft-client/actions/runs/5252759627）试试](https://github.com/Nyan-Work/oh-my-minecraft-client/actions/runs/5252759627%EF%BC%89%E8%AF%95%E8%AF%95)

没事没事 感谢

**Comment by fashion27** [comment]
替换了还是不行
![image](https://github.com/Nyan-Work/oh-my-minecraft-client/assets/109896502/42be589d-db96-4833-a422-148079c49116)

**Comment by Wudji** [comment]
> 替换了还是不行 ![image](https://user-images.githubusercontent.com/109896502/246654243-42be589d-db96-4833-a422-148079c49116.png)

新版本的整合包已经修复了这个bug。尝试将整合包更新到v5.1.2版本试试。

**Comment by Hendrix-Shen** [comment]
请尝试此版本：[0.5.294+e12a73f](https://github.com/Nyan-Work/oh-my-minecraft-client/releases/tag/nyan-work%2Fdev.25)
